### ISSUE TITLE
How to compile LAPACK and BLAS

### ISSUE THREAD

**Issue by tianfenhua123** [StarGate01/Full-Stack-Fortran#1]
Hi, I'm really excited about your work! Followed your blog and successfully got the test.f90 to run in browser. Though I haven'
t figured out how to compile LAPCK and BLAS to wasm using your method. Is it possible to provide some kind of instructions? Any help would be greatly appreciated!

**Comment by StarGate01** [comment]
Hi! Pre-compiled libraries (e.g. `/app/lib/libgfortran.a , /app/lib/liblapack.a , /app/lib/librefblas.a`) are included in the Docker image, they are built in the Dockerfile: https://github.com/StarGate01/Full-Stack-Fortran/blob/master/tools/f90wasm/Dockerfile#L37 . So to use them you just have to (statically) link against them.

If you want to compile them by youself, you can take a look at the makefile definitions I used: https://github.com/StarGate01/Full-Stack-Fortran/blob/master/tools/f90wasm/vendor/LAPACK/make.inc . To compile BLAS and LAPACK, you pretty much only have to provide this makefile config file, and `make` (or `emmake make`) will take care of the rest. This excactly what the Dockerfile does.

Note: Complex number and quad-precision types are not available (yet). At the time of writing, only the `single` and `double` targets are compiled.

**Comment by tianfenhua123** [comment]
Got it! Many thanks for the help! Your work is really helpful
