### ISSUE TITLE
Test script has `docker-compose`

### ISSUE THREAD

**Issue by rjzak** [StarGate01/Full-Stack-Fortran#8]
https://github.com/StarGate01/Full-Stack-Fortran/blob/master/test/test.sh
The script should just use `docker`

**Comment by StarGate01** [comment]
Thanks for the comment, I think this makes no difference in practice, but I agree that relying on fewer components is a good idea.

**Comment by StarGate01** [comment]
Fixed in 3676d8b072f5148d5f7acb4edc0d7048ff4f57b6 .
